# Application
spring.application.name=benefits-eligibility-api
server.port=8080

# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/benefits_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.eligibility=INFO
logging.level.org.springframework.web=WARN
